//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBuy_v2._0.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Serbian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Serbian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarBuy_v2._0.Properties.Languages.Serbian", typeof(Serbian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrazumijevana.
        /// </summary>
        public static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primjeni.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plava.
        /// </summary>
        public static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupljeno.
        /// </summary>
        public static string bought {
            get {
                return ResourceManager.GetString("bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupi.
        /// </summary>
        public static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcije.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crvena.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osvježi.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
    }
}
